# -*- coding: utf-8 -*-
import json
from pathlib import Path

def L(fr, de, es, it, ja, ko, pt):
    return {"fr": fr, "de": de, "es": es, "it": it, "ja": ja, "ko": ko, "pt": pt}

T = {}

def p(en, fr, de, es, it, ja, ko, pt):
    T[en] = L(fr, de, es, it, ja, ko, pt)

# --- remaining short/template keys + feedback UI (professional ski register) ---
p("Your skis at {own} cm sit inside that band.",
  "Vos skis à {own} cm se situent dans cette plage.",
  "Ihre Ski mit {own} cm liegen innerhalb dieses Bandes.",
  "Tus esquís de {own} cm están dentro de esa franja.",
  "I tuoi sci da {own} cm rientrano in quella fascia.",
  "{own} cmのスキーはその推奨帯の内側です。",
  "{own} cm 스키는 해당 구간 안에 있습니다.",
  "Os seus skis de {own} cm situam-se dentro dessa faixa.")
p("Your skis at {own} cm sit outside that band.",
  "Vos skis à {own} cm se situent hors de cette plage.",
  "Ihre Ski mit {own} cm liegen außerhalb dieses Bandes.",
  "Tus esquís de {own} cm están fuera de esa franja.",
  "I tuoi sci da {own} cm escono da quella fascia.",
  "{own} cmのスキーはその推奨帯の外側です。",
  "{own} cm 스키는 해당 구간 밖에 있습니다.",
  "Os seus skis de {own} cm situam-se fora dessa faixa.")
p("at least {value}",
  "au moins {value}",
  "mindestens {value}",
  "al menos {value}",
  "almeno {value}",
  "最低 {value}",
  "최소 {value}",
  "pelo menos {value}")
p("at most {n} of {total}",
  "au plus {n} sur {total}",
  "höchstens {n} von {total}",
  "como máximo {n} de {total}",
  "al massimo {n} su {total}",
  "{total}中最大{n}",
  "{total}개 중 최대 {n}",
  "no máximo {n} de {total}")
p("at most {value}",
  "au plus {value}",
  "höchstens {value}",
  "como máximo {value}",
  "al massimo {value}",
  "最大 {value}",
  "최대 {value}",
  "no máximo {value}")
p("carve",
  "carve",
  "Carve",
  "carve",
  "carve",
  "カービング",
  "카빙",
  "carve")
p("each side",
  "de chaque côté",
  "je Seite",
  "cada lado",
  "ogni lato",
  "左右各",
  "각 쪽",
  "cada lado")
p("hockey stop",
  "arrêt hockey",
  "Hockey-Stopp",
  "frenada hockey",
  "hockey stop",
  "ホッケーストップ",
  "하키스톱",
  "travagem hockey")
p("left ankle",
  "cheville gauche",
  "linkes Sprunggelenk",
  "tobillo izquierdo",
  "caviglia sinistra",
  "左足首",
  "왼쪽 발목",
  "tornozelo esquerdo")
p("left foot",
  "pied gauche",
  "linker Fuß",
  "pie izquierdo",
  "piede sinistro",
  "左足",
  "왼쪽 발",
  "pé esquerdo")
p("left heel",
  "talon gauche",
  "linke Ferse",
  "talón izquierdo",
  "tallone sinistro",
  "左かかと",
  "왼쪽 뒤꿈치",
  "calcanhar esquerdo")
p("left hip",
  "hanche gauche",
  "linke Hüfte",
  "cadera izquierda",
  "anca sinistra",
  "左股関節",
  "왼쪽 고관절",
  "anca esquerda")
p("left knee",
  "genou gauche",
  "linkes Knie",
  "rodilla izquierda",
  "ginocchio sinistro",
  "左膝",
  "왼쪽 무릎",
  "joelho esquerdo")
p("left shoulder",
  "épaule gauche",
  "linke Schulter",
  "hombro izquierdo",
  "spalla sinistra",
  "左肩",
  "왼쪽 어깨",
  "ombro esquerdo")
p("left wrist",
  "poignet gauche",
  "linkes Handgelenk",
  "muñeca izquierda",
  "polso sinistro",
  "左手首",
  "왼쪽 손목",
  "pulso esquerdo")
p("mogul",
  "bosses",
  "Buckel",
  "baches",
  "gobbe",
  "モーグル",
  "모굴",
  "moguls")
p("ollie",
  "ollie",
  "Ollie",
  "ollie",
  "ollie",
  "オリー",
  "올리",
  "ollie")
p("one-ski",
  "un ski",
  "Ein-Ski",
  "un esquí",
  "mono-sci",
  "ワンスキー",
  "원스키",
  "um ski")
p("parallel",
  "parallèle",
  "Parallel",
  "paralelo",
  "parallelo",
  "パラレル",
  "패러렐",
  "paralelo")
p("park",
  "park",
  "Park",
  "park",
  "park",
  "パーク",
  "파크",
  "park")
p("race gates",
  "portes",
  "Renntore",
  "puertas",
  "porte da gara",
  "レースゲート",
  "레이스 게이트",
  "portões")
p("right ankle",
  "cheville droite",
  "rechtes Sprunggelenk",
  "tobillo derecho",
  "caviglia destra",
  "右足首",
  "오른쪽 발목",
  "tornozelo direito")
p("right foot",
  "pied droit",
  "rechter Fuß",
  "pie derecho",
  "piede destro",
  "右足",
  "오른쪽 발",
  "pé direito")
p("right heel",
  "talon droit",
  "rechte Ferse",
  "talón derecho",
  "tallone destro",
  "右かかと",
  "오른쪽 뒤꿈치",
  "calcanhar direito")
p("right hip",
  "hanche droite",
  "rechte Hüfte",
  "cadera derecha",
  "anca destra",
  "右股関節",
  "오른쪽 고관절",
  "anca direita")
p("right knee",
  "genou droit",
  "rechtes Knie",
  "rodilla derecha",
  "ginocchio destro",
  "右膝",
  "오른쪽 무릎",
  "joelho direito")
p("right shoulder",
  "épaule droite",
  "rechte Schulter",
  "hombro derecho",
  "spalla destra",
  "右肩",
  "오른쪽 어깨",
  "ombro direito")
p("right wrist",
  "poignet droit",
  "rechtes Handgelenk",
  "muñeca derecha",
  "polso destro",
  "右手首",
  "오른쪽 손목",
  "pulso direito")
p("skid",
  "dérapage",
  "Drift",
  "derrape",
  "derapata",
  "スキッド",
  "스키드",
  "derrapagem")
p("switch",
  "switch",
  "Switch",
  "switch",
  "switch",
  "スイッチ",
  "스위치",
  "switch")
p("wedge",
  "chasse-neige",
  "Pflug",
  "cuña",
  "spazzaneve",
  "プルーク",
  "플루크",
  "cunha")
p("wedge christie",
  "christiana",
  "Christie",
  "cuña christie",
  "christie",
  "ウェッジクリスティー",
  "웨지 크리스티",
  "cunha christie")
p("{fault} in {n} of {total} transitions",
  "{fault} dans {n} transitions sur {total}",
  "{fault} in {n} von {total} Übergängen",
  "{fault} en {n} de {total} transiciones",
  "{fault} in {n} di {total} transizioni",
  "{total}回の遷移中{n}回で{fault}",
  "{total}회 전환 중 {n}회에서 {fault}",
  "{fault} em {n} de {total} transições")
p("{head} and {tail}",
  "{head} et {tail}",
  "{head} und {tail}",
  "{head} y {tail}",
  "{head} e {tail}",
  "{head}と{tail}",
  "{head} 및 {tail}",
  "{head} e {tail}")
p("{lo} to {hi}",
  "{lo} à {hi}",
  "{lo} bis {hi}",
  "{lo} a {hi}",
  "{lo} a {hi}",
  "{lo}〜{hi}",
  "{lo}~{hi}",
  "{lo} a {hi}")
p("{n} flagged",
  "{n} signalé(s)",
  "{n} markiert",
  "{n} marcados",
  "{n} segnalati",
  "{n}件フラグ",
  "{n}건 표시",
  "{n} assinalados")
p("{n} min",
  "{n} min",
  "{n} Min.",
  "{n} min",
  "{n} min",
  "{n}分",
  "{n}분",
  "{n} min")
p("{n} more rows in the full module",
  "{n} lignes de plus dans le module complet",
  "{n} weitere Zeilen im vollständigen Modul",
  "{n} filas más en el módulo completo",
  "{n} altre righe nel modulo completo",
  "完全モジュールにあと{n}行",
  "전체 모듈에 {n}행 더 있음",
  "mais {n} linhas no módulo completo")
p("{n} of {total} turns",
  "{n} virages sur {total}",
  "{n} von {total} Schwüngen",
  "{n} de {total} curvas",
  "{n} di {total} curve",
  "{total}ターン中{n}",
  "{total}회 턴 중 {n}회",
  "{n} de {total} curvas")
p("{n} of {total} turns carried this fault",
  "{n} virages sur {total} présentaient ce défaut",
  "{n} von {total} Schwüngen trugen diesen Fehler",
  "{n} de {total} curvas llevaron este fallo",
  "{n} di {total} curve presentavano questo difetto",
  "{total}ターン中{n}回でこの欠点",
  "{total}회 턴 중 {n}회에서 이 결함",
  "{n} de {total} curvas apresentaram este defeito")
p("{n} reps",
  "{n} répétitions",
  "{n} Wiederholungen",
  "{n} reps",
  "{n} ripetizioni",
  "{n}回",
  "{n}회",
  "{n} reps")
p("{n} runs",
  "{n} descentes",
  "{n} Abfahrten",
  "{n} bajadas",
  "{n} discese",
  "{n}本",
  "{n}런",
  "{n} descidas")
p("{n} sessions",
  "{n} séances",
  "{n} Einheiten",
  "{n} sesiones",
  "{n} sessioni",
  "{n}セッション",
  "{n}세션",
  "{n} sessões")
p("{n} sets",
  "{n} séries",
  "{n} Sätze",
  "{n} series",
  "{n} serie",
  "{n}セット",
  "{n}세트",
  "{n} séries")
p("{n} turns",
  "{n} virages",
  "{n} Schwünge",
  "{n} curvas",
  "{n} curve",
  "{n}ターン",
  "{n}회 턴",
  "{n} curvas")
p("{n} turns · {left} left / {right} right",
  "{n} virages · {left} gauche / {right} droite",
  "{n} Schwünge · {left} links / {right} rechts",
  "{n} curvas · {left} izq. / {right} der.",
  "{n} curve · {left} sx / {right} dx",
  "{n}ターン · 左 {left} / 右 {right}",
  "{n}회 턴 · 좌 {left} / 우 {right}",
  "{n} curvas · {left} esq. / {right} dir.")
p("{sec:.1f}s",
  "{sec:.1f}s",
  "{sec:.1f}s",
  "{sec:.1f}s",
  "{sec:.1f}s",
  "{sec:.1f}秒",
  "{sec:.1f}초",
  "{sec:.1f}s")
p("{sec:.1f}s  σ {std:.0f}",
  "{sec:.1f}s  σ {std:.0f}",
  "{sec:.1f}s  σ {std:.0f}",
  "{sec:.1f}s  σ {std:.0f}",
  "{sec:.1f}s  σ {std:.0f}",
  "{sec:.1f}秒  σ {std:.0f}",
  "{sec:.1f}초  σ {std:.0f}",
  "{sec:.1f}s  σ {std:.0f}")
p("{status} (failed, retry)",
  "{status} (échec, nouvel essai)",
  "{status} (fehlgeschlagen, erneut)",
  "{status} (fallido, reintentar)",
  "{status} (fallito, riprova)",
  "{status}（失敗、再試行）",
  "{status} (실패, 재시도)",
  "{status} (falhou, tentar de novo)")
p("—",
  "—",
  "—",
  "—",
  "—",
  "—",
  "—",
  "—")
p("Predicted passed",
  "Réussite prédite",
  "Voraussichtlich bestanden",
  "Aprobado previsto",
  "Superamento previsto",
  "合格予測",
  "통과 예측",
  "Aprovado previsto")
p("Predicted passed based on {current} result",
  "Réussite prédite d’après le résultat {current}",
  "Voraussichtlich bestanden anhand des {current}-Ergebnisses",
  "Aprobado previsto según el resultado {current}",
  "Superamento previsto in base al risultato {current}",
  "{current}の結果に基づく合格予測",
  "{current} 결과 기반 통과 예측",
  "Aprovado previsto com base no resultado {current}")
p("Correct result",
  "Corriger le résultat",
  "Ergebnis korrigieren",
  "Corregir el resultado",
  "Correggi il risultato",
  "結果を修正",
  "결과 수정",
  "Corrigir o resultado")
p("Select the actual stage:",
  "Sélectionnez le niveau réel :",
  "Tatsächliche Stufe wählen:",
  "Selecciona la etapa real:",
  "Seleziona il livello reale:",
  "実際の段階を選択：",
  "실제 단계를 선택하세요:",
  "Selecione o nível real:")
p("Detected stage: {name}",
  "Niveau détecté : {name}",
  "Erkannte Stufe: {name}",
  "Etapa detectada: {name}",
  "Livello rilevato: {name}",
  "検出段階：{name}",
  "감지된 단계: {name}",
  "Nível detetado: {name}")
p("Note (optional):",
  "Note (facultatif) :",
  "Hinweis (optional):",
  "Nota (opcional):",
  "Nota (facoltativa):",
  "メモ（任意）：",
  "메모(선택):",
  "Nota (opcional):")
p("e.g. This is a mogul skiing clip, not a basic glide",
  "ex. Ceci est un clip de ski de bosses, pas une glisse basique",
  "z. B. Das ist ein Buckel-Clip, kein einfaches Gleiten",
  "p. ej. Este es un clip de esquí de baches, no un desliz básico",
  "es. Questa è una clip di ski gobbe, non una scivolata base",
  "例：これはモーグル滑走のクリップで、基本の直進滑走ではありません",
  "예: 기본 활주가 아니라 모굴 스키 클립입니다",
  "ex. Este é um clipe de ski de moguls, não um deslize básico")
p("Your correction is saved locally and helps improve the detection algorithm.",
  "Votre correction est enregistrée localement et aide à améliorer l’algorithme de détection.",
  "Ihre Korrektur wird lokal gespeichert und hilft, den Erkennungsalgorithmus zu verbessern.",
  "Tu corrección se guarda en local y ayuda a mejorar el algoritmo de detección.",
  "La correzione è salvata in locale e aiuta a migliorare l’algoritmo di rilevamento.",
  "修正は端末に保存され、検出アルゴリズムの改善に役立ちます。",
  "수정 내용은 기기에 저장되며 감지 알고리즘 개선에 도움이 됩니다.",
  "A sua correção é guardada localmente e ajuda a melhorar o algoritmo de deteção.")
p("Wedge mogul run",
  "Descente bosses en chasse-neige",
  "Buckelpiste im Pflug",
  "Bajada de baches en cuña",
  "Discesa gobbe a spazzaneve",
  "プルーク・モーグル滑走",
  "플루크 모굴 활주",
  "Descida de moguls em cunha")
p("Navigate mogul terrain with wedge or semi-parallel; absorb bumps and stay rhythmic. Early entry into mogul skiing after wedge turns.",
  "Naviguez le terrain de bosses en chasse-neige ou semi-parallèle ; absorbez les bosses et gardez le rythme. Entrée précoce en ski de bosses après les virages en chasse-neige.",
  "Buckelgelände im Pflug oder Halbparallel befahren; Stöße absorbieren und Rhythmus halten. Früher Einstieg ins Buckelfahren nach Pflugschwüngen.",
  "Navega terreno de baches en cuña o semiparalelo; absorbe los baches y mantén el ritmo. Entrada temprana al esquí de baches tras curvas en cuña.",
  "Affronta le gobbe a spazzaneve o semi-parallelo; assorbi i dossi e resta ritmico. Ingresso precoce nello ski gobbe dopo le curve a spazzaneve.",
  "プルークまたはセミパラレルでモーグルをこなし、バンプを吸収してリズムを保つ。プルークターン後のモーグル入門。",
  "플루크 또는 세미패러렐로 모굴 지형을 통과하며 범프를 흡수하고 리듬을 유지. 플루크 턴 이후 모굴 입문.",
  "Navegue terreno de moguls em cunha ou semi-paralelo; absorva os bumps e mantenha o ritmo. Entrada precoce no ski de moguls após curvas em cunha.")
p("From wedge mogul or skid branch: absorb actively, stay on snow, do not jump.",
  "Depuis la branche bosses en chasse-neige ou dérapage : absorbez activement, restez sur la neige, ne sautez pas.",
  "Vom Pflug-Buckel- oder Drift-Zweig: aktiv absorbieren, auf dem Schnee bleiben, nicht springen.",
  "Desde la rama de baches en cuña o derrape: absorbe activamente, quédate en la nieve, no saltes.",
  "Dal ramo gobbe a spazzaneve o derapata: assorbi attivamente, resta sulla neve, non saltare.",
  "プルーク・モーグルまたはスキッド枝から：積極的に吸収し雪面に残る。ジャンプしない。",
  "플루크 모굴 또는 스키드 가지에서: 적극 흡수하고 눈 위에 머무르며 점프하지 마세요.",
  "A partir do ramo de moguls em cunha ou derrapagem: absorva ativamente, fique na neve, não salte.")

out = Path("locales/_ski_locale_fills/part07.json")
out.write_text(json.dumps(T, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("wrote", len(T), "->", out)
