# -*- coding: utf-8 -*-
import json
from pathlib import Path

def L(fr, de, es, it, ja, ko, pt):
    return dict(fr=fr, de=de, es=es, it=it, ja=ja, ko=ko, pt=pt)

T = {}

def p(en, fr, de, es, it, ja, ko, pt):
    T[en] = L(fr, de, es, it, ja, ko, pt)

p("Looks like", "Ressemble à", "Sieht aus wie", "Se parece a", "Sembra", "似ている", "비슷함", "Parece")
p("Low hands and pole rhythm", "Mains basses et rythme de bâton", "Tiefe Hände und Stockrhythmus", "Manos bajas y ritmo de bastón", "Mani basse e ritmo di bastoncino", "低い手とポールリズム", "낮은 손과 폴 리듬", "Mãos baixas e ritmo de bastão")
p("MM/dd/yyyy", "jj/MM/aaaa", "TT.MM.JJJJ", "dd/MM/aaaa", "gg/MM/aaaa", "yyyy/MM/dd", "yyyy.MM.dd", "dd/MM/aaaa")
p("MP4 (*.mp4)", "MP4 (*.mp4)", "MP4 (*.mp4)", "MP4 (*.mp4)", "MP4 (*.mp4)", "MP4 (*.mp4)", "MP4 (*.mp4)", "MP4 (*.mp4)")
p("Male", "Homme", "Männlich", "Hombre", "Uomo", "男性", "남성", "Masculino")
p("Mark in", "Marquer entrée", "In markieren", "Marcar entrada", "Segna in", "インを指定", "인 지정", "Marcar entrada")
p("Mark out", "Marquer sortie", "Out markieren", "Marcar salida", "Segna out", "アウトを指定", "아웃 지정", "Marcar saída")
p("Match {fit:.0f}% · gates {gate:.0f}% · prior {prior:.0f}%", "Correspondance {fit:.0f}% · critères {gate:.0f}% · prior {prior:.0f}%", "Treffer {fit:.0f}% · Gates {gate:.0f}% · Prior {prior:.0f}%", "Coincidencia {fit:.0f}% · criterios {gate:.0f}% · prior {prior:.0f}%", "Corrispondenza {fit:.0f}% · gate {gate:.0f}% · prior {prior:.0f}%", "一致度 {fit:.0f}% · ゲート {gate:.0f}% · 事前 {prior:.0f}%", "일치도 {fit:.0f}% · 게이트 {gate:.0f}% · 사전 {prior:.0f}%", "Correspondência {fit:.0f}% · critérios {gate:.0f}% · prior {prior:.0f}%")
p("Matched skis and separation. After passing, choose short skids or long-radius carve.", "Skis parallèles et séparation. Après validation, choisissez courts dérapages ou carving grand rayon.", "Parallele Ski und Abstand. Nach Bestehen: kurze Drifts oder Carving langer Radius.", "Esquís paralelos y separación. Tras aprobar, elige derrapes cortos o carving de radio largo.", "Sci paralleli e separazione. Dopo il passaggio, scegli derapate corte o carving a raggio lungo.", "スキー平行と上下の分離。合格後はショートスキッドかロングカービングへ。", "스키 평행과 분리. 통과 후 숏 스키드 또는 롱 카빙 선택.", "Skis paralelos e separação. Após passar, escolha derrapagens curtas ou carving de raio longo.")
p("Mean stance between a full wedge and parallel.", "Écartement moyen entre chasse-neige plein et parallèle.", "Mittlere Standbreite zwischen vollem Pflug und Parallel.", "Base media entre cuña completa y paralelo.", "Base media tra spazzaneve pieno e parallelo.", "フルプルークとパラレルの中間スタンス。", "풀 플루크와 패러렐 사이 평균 스탠스.", "Base média entre cunha completa e paralelo.")
p("Mean turn {sec:.2f}s", "Virage moyen {sec:.2f}s", "Mittlerer Schwung {sec:.2f}s", "Curva media {sec:.2f}s", "Curva media {sec:.2f}s", "平均ターン {sec:.2f}s", "평균 턴 {sec:.2f}s", "Curva média {sec:.2f}s")
p("Measured", "Mesuré", "Gemessen", "Medido", "Misurato", "実測", "실측", "Medido")
p("Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)", "Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)", "Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)", "Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)", "Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)", "Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)", "Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)", "Media (*.mp4 *.mov *.avi *.mkv *.webm *.jpg *.jpeg *.png *.webp *.bmp)")
p("Medium-radius carve", "Carving rayon moyen", "Carving mittlerer Radius", "Carving de radio medio", "Carving a raggio medio", "ミドルターン・カービング", "미들턴 카빙", "Carving de raio médio")
p("Medium-radius edge change", "Changement de carre rayon moyen", "Kantenwechsel mittlerer Radius", "Cambio de canto de radio medio", "Cambio di lama a raggio medio", "ミドルのエッジチェンジ", "미들 엣지 체인지", "Mudança de canto de raio médio")
p("Medium-turn cadence", "Cadence de virage moyen", "Mittelschwung-Kadenz", "Cadencia de curva media", "Cadenza di curva media", "ミドルターンのリズム", "미들턴 케이던스", "Cadência de curva média")
p("Missing", "Manquant", "Fehlt", "Falta", "Mancante", "欠落", "누락", "Em falta")
p("Missing model {path}. Run: python scripts/download_pose_landmarker.py", "Modèle manquant {path}. Lancez : python scripts/download_pose_landmarker.py", "Modell fehlt {path}. Ausführen: python scripts/download_pose_landmarker.py", "Falta el modelo {path}. Ejecuta: python scripts/download_pose_landmarker.py", "Modello mancante {path}. Esegui: python scripts/download_pose_landmarker.py", "モデル欠落 {path}。実行: python scripts/download_pose_landmarker.py", "모델 누락 {path}. 실행: python scripts/download_pose_landmarker.py", "Modelo em falta {path}. Execute: python scripts/download_pose_landmarker.py")
p("Moderate groomed blue run; for parallel, skids, and long-radius carve.", "Piste bleue damée modérée ; pour parallèle, dérapages et carving grand rayon.", "Mässige präparierte blaue Piste; für Parallel, Drift und Carving langer Radius.", "Pista azul pisada moderada; para paralelo, derrapes y carving de radio largo.", "Pista blu battuta moderata; per parallelo, derapate e carving a raggio lungo.", "中程度の整備青斜面。パラレル・スキッド・ロングカービング向け。", "중간 정비 블루; 패러렐·스키드·롱 카빙용.", "Pista azul preparada moderada; para paralelo, derrapagens e carving de raio longo.")
p("Mogul", "Bosse", "Buckel", "Bache", "Gobba", "モーグル", "모글", "Mogul")
p("Mogul absorption", "Absorption bosses", "Buckel-Absorption", "Absorción en baches", "Assorbimento gobbe", "モーグル吸収", "모글 흡수", "Absorção em moguls")
p("Mogul fall-line", "Ligne de pente bosses", "Buckel-Falllinie", "Línea de máxima pendiente en baches", "Linea di massima pendenza sulle gobbe", "モーグル・フォールライン", "모글 폴라인", "Linha de máxima pendente em moguls")
p("Mogul field", "Champ de bosses", "Buckelfeld", "Campo de baches", "Campo di gobbe", "モーグル畑", "모글 필드", "Campo de moguls")
p("Mogul skiing", "Ski de bosses", "Buckelfahren", "Esquí en baches", "Sci sulle gobbe", "モーグル滑走", "모글 스키", "Ski de moguls")
p("Moguls", "Bosses", "Buckel", "Baches", "Gobbe", "モーグル", "모글", "Moguls")
p("Most turns finish with a shaped arc; a slip to recover is fine, a slipped descent is not.", "La plupart des virages finissent en arc formé ; un dérapage pour récupérer va, une descente en dérapage non.", "Die meisten Schwünge enden mit geformtem Bogen; kurzer Drift zum Retten ok, Drift-Abfahrt nicht.", "La mayoría de curvas terminan en arco; un derrape para recuperar vale, un descenso derrapado no.", "La maggior parte delle curve finisce con arco sagomato; una derapata per recuperare va bene, una discesa derapata no.", "大半のターンは弧で終える。立て直しの側滑は可、ずっと横滑は不可。", "대부분 턴은 아크로 마무리. 회복용 스키드는 OK, 계속 스키드 하강은 안 됨.", "A maioria das curvas termina em arco; uma derrapagem para recuperar serve, uma descida derrapada não.")
p("Name", "Nom", "Name", "Nombre", "Nome", "氏名", "이름", "Nome")
p("Needs a scene fact", "Nécessite un fait de scène", "Braucht eine Geländeangabe", "Necesita un dato de escena", "Serve un fatto di scena", "シーン情報が必要", "장면 정보 필요", "Precisa de um facto de cena")
p("Needs a scene fact before it can be detected.", "Nécessite un fait de scène avant détection.", "Braucht eine Geländeangabe vor der Erkennung.", "Necesita un dato de escena antes de detectarse.", "Serve un fatto di scena prima del rilevamento.", "検出前にシーン情報が必要です。", "감지 전에 장면 정보가 필요합니다.", "Precisa de um facto de cena antes de ser detetado.")
p("Needs the {name} checkpoint", "Nécessite le point de contrôle {name}", "Braucht den Checkpoint {name}", "Necesita el checkpoint {name}", "Serve il checkpoint {name}", "チェックポイント「{name}」が必要", "체크포인트 \"{name}\" 필요", "Precisa do checkpoint {name}")
p("Needs work", "À améliorer", "Verbesserungsbedarf", "Hay que mejorar", "Da migliorare", "要改善", "개선 필요", "Precisa de trabalho")
p("Needs {name} first", "Nécessite d’abord {name}", "Braucht zuerst {name}", "Necesita primero {name}", "Serve prima {name}", "先に{name}が必要", "먼저 {name} 필요", "Precisa primeiro de {name}")
p("Never ski off-piste alone; avoid avalanche terrain and sidecountry, and keep a partner in sight.", "Ne skiez jamais hors-piste seul ; évitez le terrain avalancheux et le sidecountry, gardez un partenaire en vue.", "Nie allein Offpiste; Lawinengelände und Sidecountry meiden, Partner in Sicht halten.", "Nunca esquíes fuera de pista solo; evita terreno de alud y sidecountry, mantén a un compañero a la vista.", "Non sciare mai fuori pista da solo; evita terreno valanghivo e sidecountry, tieni un partner in vista.", "オフピステは単独禁止。雪崩地形・サイドカントリーを避け、仲間を視界に。", "오프피스테는 혼자 금지. 눈사태 지형·사이드컨트리 피하고 파트너를 시야에.", "Nunca esquie fora de pista sozinho; evite terreno de avalanche e sidecountry, mantenha um parceiro à vista.")
p("New profile", "Nouveau profil", "Neues Profil", "Nuevo perfil", "Nuovo profilo", "新規プロフィール", "새 프로필", "Novo perfil")
p("Next stage", "Niveau suivant", "Nächste Stufe", "Siguiente nivel", "Livello successivo", "次の段階", "다음 단계", "Próximo nível")
p("Next stage: {names}", "Niveau suivant : {names}", "Nächste Stufe: {names}", "Siguiente nivel: {names}", "Livello successivo: {names}", "次の段階：{names}", "다음 단계: {names}", "Próximo nível: {names}")
p("Next steps", "Prochaines étapes", "Nächste Schritte", "Próximos pasos", "Prossimi passi", "次のステップ", "다음 단계", "Próximos passos")
p("No box", "Pas de cadre", "Kein Rahmen", "Sin caja", "Nessun box", "枠なし", "박스 없음", "Sem caixa")
p("No braking scrape", "Pas de freinage en dérapage", "Kein Brems-Schaben", "Sin raspado de frenado", "Niente raschiata frenante", "搓雪ブレーキなし", "제동 스키드 없음", "Sem raspagem de travagem")
p("No camera found. On the emulator, use a virtual scene or webcam.", "Aucune caméra. Sur émulateur, utilisez une scène virtuelle ou une webcam.", "Keine Kamera. Am Emulator virtuelle Szene oder Webcam nutzen.", "No se encontró cámara. En el emulador usa escena virtual o webcam.", "Nessuna fotocamera. Sull’emulatore usa scena virtuale o webcam.", "カメラなし。エミュレータでは仮想シーンかウェブカメラを。", "카메라 없음. 에뮬레이터에서는 가상 장면 또는 웹캠을.", "Nenhuma câmara. No emulador use cena virtual ou webcam.")
p("No linked turns were detected in this clip.", "Aucun virage enchaîné détecté dans ce clip.", "Keine verketteten Schwünge in diesem Clip.", "No se detectaron curvas enlazadas en este clip.", "Nessuna curva concatenata in questa clip.", "このクリップに連続ターンは検出されませんでした。", "이 클립에서 연결 턴이 감지되지 않았습니다.", "Não foram detetadas curvas encadeadas neste clipe.")
p("No linked turns were detected, so turn-by-turn checkpoints are not scored. Film several linked turns.", "Aucun virage enchaîné : les points par virage ne sont pas notés. Filmez plusieurs virages enchaînés.", "Keine verketteten Schwünge: Turn-Checkpoints unbewertet. Mehrere verkettete Schwünge filmen.", "Sin curvas enlazadas: los checkpoints por curva no se puntúan. Filma varias curvas enlazadas.", "Senza curve concatenate: i checkpoint per curva non sono valutati. Riprendi più curve concatenate.", "連続ターンなしのため逐ターン採点なし。連続ターンを複数撮ってください。", "연결 턴이 없어 턴별 채점 없음. 연결 턴을 여러 개 촬영하세요.", "Sem curvas encadeadas: checkpoints por curva não pontuados. Filme várias curvas encadeadas.")
p("No pose", "Pas de pose", "Keine Pose", "Sin pose", "Nessuna posa", "姿勢なし", "자세 없음", "Sem postura")
p("No preview", "Pas d’aperçu", "Keine Vorschau", "Sin vista previa", "Nessuna anteprima", "プレビューなし", "미리보기 없음", "Sem pré-visualização")
p("No stage report yet. Analyze a clip offline first.", "Pas encore de rapport. Analysez d’abord un clip hors ligne.", "Noch kein Stufenbericht. Zuerst Clip offline analysieren.", "Aún no hay informe. Analiza primero un clip sin conexión.", "Ancora nessun report. Analizza prima una clip offline.", "段階レポートはまだありません。先にオフライン分析を。", "아직 단계 리포트 없음. 먼저 오프라인 분석을.", "Ainda sem relatório. Analise primeiro um clipe offline.")
p("No terrain suggestion at this stage; use the runs you already ski well.", "Pas de suggestion de terrain à ce niveau ; utilisez les pistes que vous maîtrisez.", "Kein Geländevorschlag auf dieser Stufe; fahre Pisten, die du schon gut kannst.", "Sin sugerencia de terreno; usa las pistas que ya esquías bien.", "Nessun suggerimento di terreno; usa le piste che già padroneggi.", "この段階では地形指定なし。得意なコースで練習を。", "이 단계에는 지형 제안 없음. 이미 잘 타는 슬로프에서.", "Sem sugestão de terreno; use as pistas que já domina.")
p("No turns were segmented in this clip.", "Aucun virage segmenté dans ce clip.", "Keine Schwünge in diesem Clip segmentiert.", "No se segmentaron curvas en este clip.", "Nessuna curva segmentata in questa clip.", "このクリップではターンが切り出せませんでした。", "이 클립에서 턴이 분할되지 않았습니다.", "Não foram segmentadas curvas neste clipe.")
p("Non-slip floor; a handhold nearby helps.", "Sol antidérapant ; une prise à portée aide.", "Rutschfester Boden; Griff in der Nähe hilft.", "Suelo antideslizante; un agarre cerca ayuda.", "Pavimento antiscivolo; un appoggio vicino aiuta.", "滑りにくい床。近くに手すりがあると安心。", "미끄럼 방지 바닥. 근처에 손잡이가 있으면 좋습니다.", "Chão antiderrapante; um apoio perto ajuda.")
p("Not applicable", "Non applicable", "Nicht anwendbar", "No aplicable", "Non applicabile", "対象外", "해당 없음", "Não aplicável")
p("Not applicable at this age.", "Non applicable à cet âge.", "In diesem Alter nicht anwendbar.", "No aplicable a esta edad.", "Non applicabile a questa età.", "この年齢では対象外。", "이 나이에는 해당 없음.", "Não aplicável nesta idade.")
p("Not judged from a clip", "Non jugeable depuis un clip", "Aus einem Clip nicht beurteilbar", "No se juzga desde un clip", "Non giudicabile da una clip", "クリップから判定不可", "클립으로 판정 불가", "Não julgável a partir de um clipe")
p("Not measured", "Non mesuré", "Nicht gemessen", "No medido", "Non misurato", "未測定", "미측정", "Não medido")
p("Not measured in this clip.", "Non mesuré dans ce clip.", "In diesem Clip nicht gemessen.", "No medido en este clip.", "Non misurato in questa clip.", "このクリップでは未測定。", "이 클립에서는 미측정.", "Não medido neste clipe.")
p("Not passed — train the lowest-scoring checkpoint.", "Non réussi — entraînez le point le plus faible.", "Nicht bestanden — niedrigsten Checkpoint trainieren.", "No aprobado — entrena el checkpoint más bajo.", "Non superato — allena il checkpoint più basso.", "未合格——得点最低のチェックポイントを訓練。", "미통과 — 최저점 체크포인트를 훈련하세요.", "Não aprovado — treine o checkpoint com pior nota.")
p("Not rated", "Non noté", "Nicht bewertet", "Sin calificar", "Non valutato", "未評価", "미평가", "Não classificado")
p("Not set", "Non renseigné", "Nicht gesetzt", "No definido", "Non impostato", "未設定", "미설정", "Não definido")
p("Not sure", "Pas sûr", "Unsicher", "No seguro", "Non sicuro", "不明", "잘 모르겠음", "Não tenho a certeza")
p("Not yet", "Pas encore", "Noch nicht", "Todavía no", "Non ancora", "まだ", "아직", "Ainda não")
p("Note", "Note", "Hinweis", "Nota", "Nota", "メモ", "메모", "Nota")
p("Nothing could be measured for this stage in this clip; re-film before training to a number.", "Rien n’a pu être mesuré pour ce niveau ; refilmez avant de viser un chiffre.", "Für diese Stufe nichts messbar; neu filmen, bevor du auf eine Zahl trainierst.", "Nada medible para este nivel; vuelve a filmar antes de entrenar a un número.", "Nulla misurabile per questo livello; riprendi prima di allenarti su un numero.", "この段階の指標は測れませんでした。数値練習の前に撮り直してください。", "이 단계 지표를 측정할 수 없습니다. 숫자 훈련 전에 다시 촬영하세요.", "Nada mensurável para este nível; volte a filmar antes de treinar para um número.")
p("OK", "OK", "OK", "OK", "OK", "OK", "확인", "OK")
p("Off-piste", "Hors-piste", "Offpiste", "Fuera de pista", "Fuori pista", "オフピステ", "오프피스테", "Fora de pista")
p("Off-piste (inside the resort boundary)", "Hors-piste (dans les limites de la station)", "Offpiste (innerhalb der Gebietsgrenze)", "Fuera de pista (dentro del dominio)", "Fuori pista (dentro del comprensorio)", "オフピステ（ゲレンデ境界内）", "오프피스테（리조트 경계 내）", "Fora de pista (dentro do domínio)")
p("Off-piste and soft snow", "Hors-piste et neige souple", "Offpiste und weicher Schnee", "Fuera de pista y nieve blanda", "Fuori pista e neve morbida", "オフピステと柔らかい雪", "오프피스테와 부드러운 눈", "Fora de pista e neve macia")
p("Ollie", "Ollie", "Ollie", "Ollie", "Ollie", "オリ―", "올리", "Ollie")
p("Play", "Lecture", "Wiedergabe", "Reproducir", "Play", "再生", "재생", "Reproduzir")
p("Pause", "Pause", "Pause", "Pausa", "Pausa", "一時停止", "일시정지", "Pausa")
p("Piste", "Piste", "Piste", "Pista", "Pista", "ゲレンデ", "슬로프", "Pista")
p("Park", "Park", "Park", "Park", "Park", "パーク", "파크", "Park")
p("Pending", "En attente", "Ausstehend", "Pendiente", "In attesa", "保留", "대기", "Pendente")
p("Pass", "Réussi", "Bestanden", "Aprobado", "Superato", "合格", "통과", "Aprovado")
p("Parallel skiing", "Ski parallèle", "Parallelfahren", "Esquí paralelo", "Sci parallelo", "パラレル滑走", "패러렐 스키", "Ski paralelo")
p("Parallel stance", "Écartement parallèle", "Parallel-Standbreite", "Base paralela", "Base parallela", "パラレルスタンス", "패러렐 스탠스", "Base paralela")
p("Packed", "Tassée", "Festgefahren", "Pisada", "Compatta", "圧雪", "다져진 눈", "Compactada")
p("Packed powder", "Poudreuse tassée", "Festgefahrener Pulver", "Polvo pisado", "Polvere compatta", "圧実パウダー", "다진 파우더", "Powder compactada")
p("Panning", "Panoramique", "Schwenken", "Paneo", "Panoramica", "パン", "패닝", "Panorâmica")
p("Panning camera", "Caméra en panoramique", "Schwenkende Kamera", "Cámara en paneo", "Camera in panoramica", "パンカメラ", "패닝 카메라", "Câmara em panorâmica")
p("Other", "Autre", "Divers", "Otro", "Altro", "その他", "기타", "Outro")
p("Out", "Sortie", "Out", "Salida", "Out", "アウト", "아웃", "Saída")
p("Name", "Nom", "Name", "Nombre", "Nome", "氏名", "이름", "Nome")

out = Path("locales/_ski_locale_fills/part03.json")
out.write_text(json.dumps(T, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("wrote", len(T), "->", out)
