from __future__ import annotations

from core.sports.catalog.helpers import checkpoint


def checkpoints() -> list[dict]:
    return [
        checkpoint(
            "cp_pg_stance",
            "Wedge stance",
            "Tips close, tails open, stance wider than the hips.",
            ["ankle", "knee", "hip"],
            "stance_width",
            "between",
            1.15,
            ["drill_wedge_stop"],
            hi=2.5,
        ),
        checkpoint(
            "cp_pg_knee",
            "Soft knees and ankles",
            "Elastic knees and ankles; not locked.",
            ["ankle", "knee"],
            "knee_flex_mean",
            "gte",
            12.0,
            ["drill_land_stance", "drill_land_squat"],
        ),
        checkpoint(
            "cp_pg_com",
            "Center of mass not backseat",
            "Hips over the feet; pressure into the ski.",
            ["hip", "com"],
            "backseat",
            "lte",
            1.35,
            ["drill_land_stance"],
        ),
        checkpoint(
            "cp_pg_valgus",
            "Knees track",
            "Knees track over the toes; don't let the knees collapse inward.",
            ["knee"],
            "knee_valgus",
            "lte",
            1.5,
            ["drill_land_stance"],
        ),
        checkpoint(
            "cp_pz_stance",
            "Wedge through the turn",
            "Stay in a wedge through the turn; load the outside ski.",
            ["ankle", "hip"],
            "stance_width",
            "between",
            1.15,
            ["drill_wedge_c"],
            hi=2.4,
        ),
        checkpoint(
            "cp_pz_hip_ir",
            "Hip internal-rotation steering",
            "Heuristic: steer with the legs — rotate the femurs so the ski tips turn while the torso stays quiet.",
            ["hip", "knee"],
            "hip_ir_proxy",
            "gte",
            0.08,
            ["drill_hip_steer"],
        ),
        checkpoint(
            "cp_pz_knee",
            "Flex into the turn",
            "Slightly lower in the turn; elastic knees.",
            ["knee", "com"],
            "knee_flex_mean",
            "gte",
            12.0,
            ["drill_land_squat"],
        ),
        checkpoint(
            "cp_pz_turn",
            "Linked turns",
            "Left-right turns, not a straight schuss.",
            ["com"],
            "turn_freq",
            "gte",
            0.15,
            ["drill_wedge_c"],
        ),
        checkpoint(
            "cp_pz_upper",
            "Torso downhill",
            "Do not spin the shoulders with the skis.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.45,
            ["drill_hands"],
            required=False,
        ),
        checkpoint(
            "cp_pz_gaze",
            "Look downhill",
            "Unscored when the head is not visible in 2D pose.",
            ["neck", "gaze"],
            "gaze_ok",
            "gte",
            0.5,
            ["drill_wedge_c"],
            required=False,
        ),
        checkpoint(
            "cp_wc_openclose",
            "Open then close",
            "Stance width varies; not a locked wedge the whole turn.",
            ["ankle", "hip"],
            "stance_width_std",
            "gte",
            0.18,
            ["drill_christie"],
        ),
        checkpoint(
            "cp_wc_stance",
            "Christie stance",
            "Mean stance between a full wedge and parallel.",
            ["ankle"],
            "stance_width",
            "between",
            0.95,
            ["drill_christie"],
            hi=1.45,
        ),
        checkpoint(
            "cp_par_stance",
            "Parallel stance",
            "About hip-width; wider usually means you're still in a wedge.",
            ["ankle", "hip"],
            "stance_width",
            "between",
            0.65,
            ["drill_land_stance"],
            hi=1.12,
        ),
        checkpoint(
            "cp_par_upper",
            "Upper-lower separation",
            "Legs move; the torso stays quieter.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.4,
            ["drill_hands"],
        ),
        checkpoint(
            "cp_par_com",
            "Outside-ski center of mass",
            "Stay centered so you can move onto the new outside ski.",
            ["com", "hip"],
            "backseat",
            "lte",
            1.35,
            ["drill_land_squat"],
        ),
        checkpoint(
            "cp_sk_hockey",
            "Hockey-stop capacity",
            "Show you can stop on command with parallel skis (both directions).",
            ["knee", "ankle", "hip"],
            "knee_flex_amp",
            "gte",
            18.0,
            ["drill_hockey"],
        ),
        checkpoint(
            "cp_sk_rhythm",
            "Short-turn cadence",
            "Quick left-right; no long traverse.",
            ["com"],
            "turn_freq",
            "gte",
            0.4,
            ["drill_skid_short"],
        ),
        checkpoint(
            "cp_sk_knee",
            "Flex for rhythm",
            "Don't land or absorb with locked, straight legs.",
            ["knee"],
            "knee_flex_mean",
            "gte",
            14.0,
            ["drill_skid_short", "drill_land_squat"],
        ),
        checkpoint(
            "cp_sk_hands",
            "Hands low",
            "Wrists below the shoulders.",
            ["hands"],
            "hands_low",
            "gte",
            0.55,
            ["drill_hands"],
            required=False,
        ),
        checkpoint(
            "cp_cv_oneski",
            "Inclination into the turn",
            "Tip the body into the turn (hips inside the arc). Heuristic only — not a measured edge angle or FIS score.",
            ["hip", "knee", "com"],
            "inward_lean",
            "gte",
            0.16,
            ["drill_one_ski", "drill_carve_round"],
            heuristic=True,
        ),
        checkpoint(
            "cp_cv_parallel",
            "Carve parallel",
            "Stay parallel or inclination becomes banking.",
            ["ankle"],
            "stance_width",
            "between",
            0.65,
            ["drill_one_ski"],
            hi=1.1,
            heuristic=True,
        ),
        checkpoint(
            "cp_cv_upper",
            "Quiet shoulders",
            "Throwing the shoulders wrecks inclination.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.42,
            ["drill_hands"],
            heuristic=True,
        ),
        checkpoint(
            "cp_cvm_freq",
            "Medium-turn cadence",
            "Edge changes faster than long-radius.",
            ["com"],
            "turn_freq",
            "gte",
            0.32,
            ["drill_carve_medium"],
            heuristic=True,
        ),
        checkpoint(
            "cp_cvs_freq",
            "Short-carve cadence",
            "Higher cadence without losing inclination.",
            ["com"],
            "turn_freq",
            "gte",
            0.45,
            ["drill_carve_short"],
            heuristic=True,
        ),
        checkpoint(
            "cp_mg_amp",
            "Knee absorption travel",
            "Large knee travel; stay on snow rather than jumping.",
            ["knee", "ankle"],
            "knee_flex_amp",
            "gte",
            30.0,
            ["drill_mogul_absorb"],
        ),
        checkpoint(
            "cp_mg_quiet",
            "Quiet upper body",
            "Let the legs do the work.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.5,
            ["drill_mogul_absorb"],
        ),
        checkpoint(
            "cp_mg_freq",
            "Bump cadence",
            "Knee flex cadence matches the bumps.",
            ["knee"],
            "knee_flex_freq",
            "gte",
            0.7,
            ["drill_mogul_line"],
        ),
        checkpoint(
            "cp_mg_fall",
            "Stay near the fall line",
            "Link bumps near the fall line with less traversing.",
            ["hip", "com"],
            "fall_line",
            "lte",
            1.2,
            ["drill_mogul_line"],
            required=False,
        ),
    ]
