"""Checkpoints for the ski curriculum.

Two flavours live here:

* ``checkpoint(...)`` — v2 rows keyed to a whole-clip **signal** id
  (``content/ski/knowledge/signals.json``). Thresholds are unchanged.
* ``metric_checkpoint(...)`` — v3 rows keyed to a **metric** id
  (``content/ski/knowledge/metrics.json``, design doc §3.4), one per gate metric
  of the new stages.

CALIBRATION NOTE — the v3 threshold values below are **first-pass expert
estimates, not calibrated bands**. The design doc's §6 fixes the scoring shape
but no numeric bands, and the new metrics (edge_angle_proxy,
pressure_peak_phase, pole_touch_rate, turn_duration_var, edge_change_duration,
braking_count, com_vertical_travel, turn_shape_index, separation_angle,
upper_body_quiet in degrees) have never been measured on real clips in this
repo. Every ``metric_checkpoint`` threshold must be re-fitted against a labelled
clip set before any of it is shown as a pass/fail to a skier.
"""

from __future__ import annotations

from core.sports.catalog.helpers import checkpoint, metric_checkpoint


def checkpoints() -> list[dict]:
    return [
        checkpoint(
            "cp_pg_stance",
            "Wedge stance",
            "Tips close, tails open, stance wider than the hips.",
            ["ankle", "knee", "hip"],
            "stance_width",
            "between",
            1.15,
            ["drill_wedge_stop"],
            hi=2.5,
        ),
        checkpoint(
            "cp_pg_knee",
            "Soft knees and ankles",
            "Elastic knees and ankles; not locked.",
            ["ankle", "knee"],
            "knee_flex_mean",
            "gte",
            12.0,
            ["drill_land_stance", "drill_land_squat"],
        ),
        checkpoint(
            "cp_pg_com",
            "Center of mass not backseat",
            "Hips over the feet; pressure into the ski.",
            ["hip", "com"],
            "backseat",
            "lte",
            1.35,
            ["drill_land_stance"],
        ),
        checkpoint(
            "cp_pg_valgus",
            "Knees track",
            "Knees track over the toes; don't let the knees collapse inward.",
            ["knee"],
            "knee_valgus",
            "lte",
            1.5,
            ["drill_land_stance"],
        ),
        checkpoint(
            "cp_pz_stance",
            "Wedge through the turn",
            "Stay in a wedge through the turn; load the outside ski.",
            ["ankle", "hip"],
            "stance_width",
            "between",
            1.15,
            ["drill_wedge_c"],
            hi=2.4,
        ),
        checkpoint(
            "cp_pz_hip_ir",
            "Hip internal-rotation steering",
            "Heuristic: steer with the legs — rotate the femurs so the ski tips turn while the torso stays quiet.",
            ["hip", "knee"],
            "hip_ir_proxy",
            "gte",
            0.08,
            ["drill_hip_steer"],
        ),
        checkpoint(
            "cp_pz_knee",
            "Flex into the turn",
            "Slightly lower in the turn; elastic knees.",
            ["knee", "com"],
            "knee_flex_mean",
            "gte",
            12.0,
            ["drill_land_squat"],
        ),
        checkpoint(
            "cp_pz_turn",
            "Linked turns",
            "Left-right turns, not a straight schuss.",
            ["com"],
            "turn_freq",
            "gte",
            0.15,
            ["drill_wedge_c"],
        ),
        checkpoint(
            "cp_pz_upper",
            "Torso downhill",
            "Do not spin the shoulders with the skis.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.45,
            ["drill_hands"],
            required=False,
        ),
        checkpoint(
            "cp_pz_gaze",
            "Look downhill",
            "Unscored when the head is not visible in 2D pose.",
            ["neck", "gaze"],
            "gaze_ok",
            "gte",
            0.5,
            ["drill_wedge_c"],
            required=False,
        ),
        checkpoint(
            "cp_wc_openclose",
            "Open then close",
            "Stance width varies; not a locked wedge the whole turn.",
            ["ankle", "hip"],
            "stance_width_std",
            "gte",
            0.18,
            ["drill_christie"],
        ),
        checkpoint(
            "cp_wc_stance",
            "Christie stance",
            "Mean stance between a full wedge and parallel.",
            ["ankle"],
            "stance_width",
            "between",
            0.95,
            ["drill_christie"],
            hi=1.45,
        ),
        checkpoint(
            "cp_par_stance",
            "Parallel stance",
            "About hip-width; wider usually means you're still in a wedge.",
            ["ankle", "hip"],
            "stance_width",
            "between",
            0.65,
            ["drill_land_stance"],
            hi=1.12,
        ),
        checkpoint(
            "cp_par_upper",
            "Upper-lower separation",
            "Legs move; the torso stays quieter.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.4,
            ["drill_hands"],
        ),
        checkpoint(
            "cp_par_com",
            "Outside-ski center of mass",
            "Stay centered so you can move onto the new outside ski.",
            ["com", "hip"],
            "backseat",
            "lte",
            1.35,
            ["drill_land_squat"],
        ),
        checkpoint(
            "cp_sk_hockey",
            "Hockey-stop capacity",
            "Show you can stop on command with parallel skis (both directions).",
            ["knee", "ankle", "hip"],
            "knee_flex_amp",
            "gte",
            18.0,
            ["drill_hockey"],
        ),
        checkpoint(
            "cp_sk_rhythm",
            "Short-turn cadence",
            "Quick left-right; no long traverse.",
            ["com"],
            "turn_freq",
            "gte",
            0.4,
            ["drill_skid_short"],
        ),
        checkpoint(
            "cp_sk_knee",
            "Flex for rhythm",
            "Don't land or absorb with locked, straight legs.",
            ["knee"],
            "knee_flex_mean",
            "gte",
            14.0,
            ["drill_skid_short", "drill_land_squat"],
        ),
        checkpoint(
            "cp_sk_hands",
            "Hands low",
            "Wrists below the shoulders.",
            ["hands"],
            "hands_low",
            "gte",
            0.55,
            ["drill_hands"],
            required=False,
        ),
        checkpoint(
            "cp_cv_oneski",
            "Inclination into the turn",
            "Tip the body into the turn (hips inside the arc). Heuristic only — not a measured edge angle or FIS score.",
            ["hip", "knee", "com"],
            "inward_lean",
            "gte",
            0.16,
            ["drill_one_ski", "drill_carve_round"],
            heuristic=True,
        ),
        checkpoint(
            "cp_cv_parallel",
            "Carve parallel",
            "Stay parallel or inclination becomes banking.",
            ["ankle"],
            "stance_width",
            "between",
            0.65,
            ["drill_one_ski"],
            hi=1.1,
            heuristic=True,
        ),
        checkpoint(
            "cp_cv_upper",
            "Quiet shoulders",
            "Throwing the shoulders wrecks inclination.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.42,
            ["drill_hands"],
            heuristic=True,
        ),
        checkpoint(
            "cp_cvm_freq",
            "Medium-turn cadence",
            "Edge changes faster than long-radius.",
            ["com"],
            "turn_freq",
            "gte",
            0.32,
            ["drill_carve_medium"],
            heuristic=True,
        ),
        checkpoint(
            "cp_cvs_freq",
            "Short-carve cadence",
            "Higher cadence without losing inclination.",
            ["com"],
            "turn_freq",
            "gte",
            0.45,
            ["drill_carve_short"],
            heuristic=True,
        ),
        checkpoint(
            "cp_mg_amp",
            "Knee absorption travel",
            "Large knee travel; stay on snow rather than jumping.",
            ["knee", "ankle"],
            "knee_flex_amp",
            "gte",
            30.0,
            ["drill_mogul_absorb"],
        ),
        checkpoint(
            "cp_mg_quiet",
            "Quiet upper body",
            "Let the legs do the work.",
            ["chest"],
            "upper_quiet",
            "lte",
            0.5,
            ["drill_mogul_absorb"],
        ),
        checkpoint(
            "cp_mg_freq",
            "Bump cadence",
            "Knee flex cadence matches the bumps.",
            ["knee"],
            "knee_flex_freq",
            "gte",
            0.7,
            ["drill_mogul_line"],
        ),
        checkpoint(
            "cp_mg_fall",
            "Stay near the fall line",
            "Link bumps near the fall line with less traversing.",
            ["hip", "com"],
            "fall_line",
            "lte",
            1.2,
            ["drill_mogul_line"],
            required=False,
        ),
        # ------------------------------------------------------------------
        # v3 metric-backed gates. All thresholds below are FIRST-PASS EXPERT
        # ESTIMATES awaiting calibration — see the module docstring.
        # ------------------------------------------------------------------
        # sideslip (st-04): gates edge_angle_proxy, upper_body_quiet
        metric_checkpoint(
            "cp_ss_edge",
            "Edge release and re-set",
            "Flatten both skis to slip sideways, then edge again to stop — neither a locked edge nor a free slide.",
            ["ankle", "knee"],
            "edge_angle_proxy",
            "between",
            5.0,  # estimate: below this the skis are flat and running away
            ["drill_sideslip"],
            hi=25.0,  # estimate: above this the edge grips and the slip stops
        ),
        metric_checkpoint(
            "cp_ss_quiet",
            "Torso faces downhill",
            "The shoulders stay square to the fall line while the skis slip.",
            ["chest"],
            "upper_body_quiet",
            "lte",
            6.0,  # estimate: std of separation_angle, in degrees
            ["drill_sideslip", "drill_hands"],
        ),
        # dynamic_parallel (st-07): gates pressure_peak_phase, pole_touch_rate,
        # turn_duration_var
        metric_checkpoint(
            "cp_dp_pressure",
            "Pressure peaks in the shaping phase",
            "Deepest flexion in the middle of the arc, not at the finish — no park-and-ride.",
            ["knee", "hip"],
            "pressure_peak_phase",
            "between",
            0.35,  # estimate: 0 = initiation, 1 = finish; shaping is the middle third
            ["drill_flex_extend"],
            hi=0.7,
        ),
        metric_checkpoint(
            "cp_dp_pole",
            "Pole touch every turn",
            "A light pole touch at each edge change, hands kept in front.",
            ["hands"],
            "pole_touch_rate",
            "gte",
            0.8,  # estimate: a touch on 8 of 10 turns
            ["drill_hands"],
        ),
        metric_checkpoint(
            "cp_dp_rhythm",
            "Even turn rhythm",
            "Turn durations stay close to each other; no long traverse between turns.",
            ["hip", "com"],
            "turn_duration_var",
            "lte",
            0.2,  # estimate: CV of turn duration
            ["drill_flex_extend", "drill_skid_short"],
        ),
        # firm_snow (st-08): gates edge_change_duration, braking_count
        metric_checkpoint(
            "cp_fs_edgechange",
            "Quick edge change on firm snow",
            "Cross from edge to edge quickly; a ski left flat slides away on hardpack.",
            ["ankle", "knee"],
            "edge_change_duration",
            "lte",
            0.35,  # estimate: seconds in the transition window
            ["drill_firm_edge"],
        ),
        metric_checkpoint(
            "cp_fs_braking",
            "No braking scrape",
            "Control speed with turn shape, not by scraping the tails across the fall line.",
            ["hip", "com"],
            "braking_count",
            "lte",
            2.0,  # estimate: the curriculum's allowance of 2 faulty turns in 20
            ["drill_firm_edge", "drill_carve_round"],
        ),
        # steeps (st-12): gates separation_angle, braking_count
        metric_checkpoint(
            "cp_st_separation",
            "Upper body down the fall line",
            "The shoulders keep facing down the pitch while the legs turn underneath.",
            ["chest", "hip"],
            "separation_angle",
            "gte",
            25.0,  # estimate: degrees of shoulder-to-pelvis separation
            ["drill_steep_pivot"],
        ),
        metric_checkpoint(
            "cp_st_braking",
            "Turn instead of side-slipping the pitch",
            "Most turns finish with a shaped arc; a slip to recover is fine, a slipped descent is not.",
            ["hip", "com"],
            "braking_count",
            "lte",
            3.0,  # estimate: a wider allowance than firm_snow, steeps are defensive
            ["drill_steep_pivot", "drill_hockey"],
        ),
        # powder (st-14): gates com_vertical_travel, turn_shape_index
        metric_checkpoint(
            "cp_pw_travel",
            "Flex and extend to surface the skis",
            "Clear up-and-down movement in every turn; a static stance sinks the tips.",
            ["hip", "com"],
            "com_vertical_travel",
            "gte",
            0.1,  # estimate: hip_y range within a turn ÷ leg length
            ["drill_powder_bounce"],
        ),
        metric_checkpoint(
            "cp_pw_shape",
            "Round turns in soft snow",
            "Keep the arc round with both skis working; do not throw the skis sideways.",
            ["hip", "com"],
            "turn_shape_index",
            "between",
            0.4,  # estimate: shaping-phase share of the turn; below = Z-shape
            ["drill_powder_bounce"],
            hi=0.75,
        ),
    ]
